	AREA PROGRAM,CODE,READONLY
	ENTRY
MAIN
	LDR R1,VALUE1
	MOV R2,#'A'
	MOV R5,#6
LOOP
	LDRB R3,[R1],#1
	CMP R3,R2
	ADDEQ R4,R4,#1
	SUBS R5,R5,#1
	BNE LOOP
	AREA PROGRAM,DATA,READONLY
VALUE1 DCD STRING
STRING DCB "ADAMAY"
	END